### ISSUE TITLE
Fix text in README

### ISSUE THREAD

**Issue by DhanshreeA** [good-data-institute/d4g-cohort-2024-hackathon#5]
[Section heading](https://github.com/good-data-institute/d4g-cohort-2024-hackathon?tab=readme-ov-file#workflows-used-by-ersilia-to-collect-internal-these-stats-for-inspiration) should read: "Workflows used by Ersilia to collect internal stats, for inspiration".

**Comment by vivekkatial** [comment]
sorted!
